cmake_minimum_required(VERSION 3.8)
project(inspection_robot_core)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(inspection_robot_interfaces REQUIRED)
add_executable(velocity_manager_node src/velocity_manager_node.cpp)
ament_target_dependencies(velocity_manager_node rclcpp geometry_msgs inspection_robot_interfaces)
install(TARGETS velocity_manager_node DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY config launch DESTINATION share/${PROJECT_NAME})
ament_package()
